### ISSUE TITLE
Results don't match the ones from Search Code on Studio

### ISSUE THREAD

**Issue by EmmaMourte** [jacebenson/servicenow-code#8]
### Results from application
![image](https://user-images.githubusercontent.com/37108977/75696401-d1f6d900-5cab-11ea-8f43-922331fd3057.png)

### Results from Search Code
![image](https://user-images.githubusercontent.com/37108977/75696587-1b472880-5cac-11ea-8c71-d27e9ce9b69b.png)

Not sure if the HTML field is responsible for this behaviour

**Comment by jacebenson** [comment]
This really helps me understand the issue.

**Comment by jacebenson** [comment]
I do know that the filter applied for that table, "Email Template[sysevent_email_action] I have a filter of "active=true"
![image](https://user-images.githubusercontent.com/638764/75699387-00f25800-5c76-11ea-80c1-303952a73d40.png)

I'm not seeing why the results are different though.

**Comment by EmmaMourte** [comment]
I saw your filter.
Removing it doesn't change anything.

**Comment by jacebenson** [comment]
I'm still looking.  It's bizarre.

**Comment by EmmaMourte** [comment]
### Another example
![image](https://user-images.githubusercontent.com/37108977/75701897-da074680-5cb4-11ea-97f8-8410ae1f4cc6.png)
![image](https://user-images.githubusercontent.com/37108977/75701940-e9868f80-5cb4-11ea-8c04-774336111b26.png)
### More
![image](https://user-images.githubusercontent.com/37108977/75702028-06bb5e00-5cb5-11ea-932b-9ce89bed702a.png)
![image](https://user-images.githubusercontent.com/37108977/75702066-163aa700-5cb5-11ea-9e3b-88be267f7806.png)

It always seems to be Notification (sysevent_email_action) table

**Comment by jacebenson** [comment]
So you can try the query in the rest api explorer, Im still digging but likely wont make headway till tonight.

**Comment by EmmaMourte** [comment]
sorry for the late response but it's quite busy these days. I tried to API explorer but didn't manage to properly populate the parameters for it. Could you provide an example ?
Also I am having these errors on the logs
![image](https://user-images.githubusercontent.com/37108977/75794082-94a84f00-5d70-11ea-8d36-a4ade1a88265.png)

**Comment by jacebenson** [comment]
No worries.  We're all busy.  
This is how my calls are made 
![image](https://user-images.githubusercontent.com/638764/75799216-63faf200-5d3d-11ea-8e6c-0a5ccab1b7d9.png)
If you want to try SN's grouping, just clear the search group and it should default to the oob grouping

**Comment by EmmaMourte** [comment]
![image](https://user-images.githubusercontent.com/37108977/75823756-9854c980-5da2-11ea-919c-0eee1df20491.png)
Rest API Call is also fetching the wrong result.

Same goes if i try to search for something like "\<p>" 
![image](https://user-images.githubusercontent.com/37108977/75824065-29c43b80-5da3-11ea-8590-29d15aa66bc9.png)
While studio search returns
![image](https://user-images.githubusercontent.com/37108977/75824268-83c50100-5da3-11ea-9b9d-8a59003e212f.png)

**Comment by EmmaMourte** [comment]
I am guessing you have followed the UI page "CodeSearchExampleUse" for your code and the REST call build..
Something more interesting.. If I use the endpoint on that UI page I get the same "wrong" results.
![image](https://user-images.githubusercontent.com/37108977/75825108-09957c00-5da5-11ea-934d-43429cdca36f.png)
![image](https://user-images.githubusercontent.com/37108977/75825121-11edb700-5da5-11ea-9b3e-01f86fb94ad8.png)

**Comment by EmmaMourte** [comment]
![image](https://user-images.githubusercontent.com/37108977/75827950-0b623e00-5dab-11ea-870c-f5f412ad0943.png)
found the solution. Set the search group to "sn_devstudio.Studio Search Group"

**Comment by EmmaMourte** [comment]
Or check the box "extended_matching" in your search group
![image](https://user-images.githubusercontent.com/37108977/75828438-21bcc980-5dac-11ea-94fd-0f1d2ee1f6e8.png)

**Comment by jacebenson** [comment]
What does extend matching do?!?  Emma great find.

**Comment by jacebenson** [comment]
I've updated this to have that checked now.  If you installed via git, a pull from source will update it.

**Comment by EmmaMourte** [comment]
![image](https://user-images.githubusercontent.com/37108977/75872353-45b0f700-5e0e-11ea-81ba-57bd9621abc4.png)
Pretty much it tells the system to also search in fields longer than 80 characters. Funny thing is that I don't find the initial limitation of "less than 80 characters" when they are querying
